[build]
  command = "npm run clean && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Optimize build for smaller functions
  NODE_OPTIONS = "--max-old-space-size=4096"

# Enhanced function configuration to reduce size
[functions]
  # External modules to reduce function bundle size
  external_node_modules = ["sharp", "canvas", "bcryptjs", "next-auth", "swiper", "bootstrap"]
  
# Exclude more files to reduce function size
[functions.excluded_files]
  ".next/cache/**" = true
  ".next/standalone/**" = true
  ".next/static/**" = true
  "node_modules/**" = true
  "*.map" = true
  "*.md" = true
  ".git/**" = true
  "public/**" = true

# Function timeout configuration
[functions."*"]
  timeout = 30

# Image optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for Next.js app router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = false

# Image optimization redirects
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

# Headers for static assets - better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Headers for images
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"