[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Function configuration to reduce size
[functions]
  external_node_modules = ["firebase", "firebase-admin"]
  
[functions.excluded_files]
  # Exclude large cache and build artifacts that cause 250MB limit issues
  ".next/cache/**" = true
  ".next/standalone/**" = true
  "node_modules/**" = true

# Redirects for Next.js app router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"