[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase function timeout
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"
  
  # Reduce function size by excluding unnecessary files
  included_files = ["public/**/*"]

# Headers for better caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for Next.js
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images?url=:splat"
  status = 200

# Edge functions (alternative to serverless)
[edge_functions]
  # Use edge functions for better performance and smaller size
  
# Build optimizations
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true