[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Function configuration
[functions]
  # Reduce function size by excluding unnecessary files
  included_files = [
    ".next/server/**",
    ".next/static/**", 
    ".next/*.json",
    "public/**"
  ]
  
  # Exclude large cache and build artifacts
  excluded_files = [
    ".next/cache/**",
    ".next/standalone/**",
    "node_modules/**"
  ]

# Redirects for Next.js app router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"